### ISSUE TITLE
The dropdown menu for the Combo node does not stay fixed.

### ISSUE THREAD

**Issue by toyxyz** [chrisgoringe/cg-use-everywhere#384]
Thanks for the awesome work as always! I'm testing a new combo node and encountered a strange error. When I copy the sampler name from ksampler and connect it to an anything node, then press start it resets to the copied value no matter what I select from the dropdown list. 

https://github.com/user-attachments/assets/fc1f0d03-c908-453f-ac58-38b577cca785

**Comment by chrisgoringe** [comment]
By "press start" do you mean when you run the workflow?

Fotos you press f12 and look for any errors in the JavaScript log?

**Comment by chrisgoringe** [comment]
Try updating to 7.2.1, I think this is fixed

**Comment by toyxyz** [comment]
Yes. There is an issue where nodes reset when running the workflow. Here are the logs. 
It is likely that “Resetting combo clone node” is the cause. 
I deleted the custom node and reinstalled it. But the problem remains the same.
<img width="834" height="368" alt="Image" src="https://github.com/user-attachments/assets/366e7aeb-0c43-4427-bdb4-3ed5dc8bdbfa" />

**Comment by chrisgoringe** [comment]
@toyxyz 
Please let me know if the problem is still occurring. I just retested and believe it to be fixed.

**Comment by toyxyz** [comment]
I completely deleted the custom node and reinstalled it. However, the same issue persists. 

https://github.com/user-attachments/assets/0744076c-06a1-4d61-94dc-7577709d507f

**Comment by chrisgoringe** [comment]
I've just update to 7.2.2 - please see if that fixes it for you.

**Comment by toyxyz** [comment]
Everything is working properly now! Thank you. 
<img width="1014" height="531" alt="Image" src="https://github.com/user-attachments/assets/f464b937-27f7-4fa0-8950-c3a454933f36" />
